apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv
  labels:
    pv: gluster-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - log-level=DEBUG
  glusterfs:
    path: /gv0
    endpoints: glusterfs-cluster 

